[package]
name = "web3-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
hex = "0.4"
assert_cmd = "2"
predicates = "3"